### ISSUE TITLE
Minimal Admin theme layout on admin/structure/types/manage/page/fields seems broken

### ISSUE THREAD

**Issue by aschmoe** [albatrossdigital/helm#10]
![download 2](https://cloud.githubusercontent.com/assets/1634686/6649153/340d1706-c9a1-11e4-8fba-4591a3ad8796.jpg)

**Comment by jlyon** [comment]
yeah it's the vertical_tabs_responsive module.   If you add `admin/*` to the blacklist on http://helm-blank.local/admin/config/user-interface/vertical_tabs_responsive it fixes it, but causes problems on other pages (features).  Still need to evaluate this.  Ideally we would be able to do the vertical tabs in the sidebar on node/*/edit without a module (just in the admin theme)...

leaving open

**Comment by aschmoe** [comment]
With removal of that vertical tabs module, this should be resoved
