### ISSUE TITLE
Remove Panopoly dependency altogether

### ISSUE THREAD

**Issue by aschmoe** [albatrossdigital/helm#14]
Down the road nice-to-have.  Currently depending on panopoly for panel panes defined in panopoly_widgets, which of course requires panopoly_core

**Comment by jlyon** [comment]
Depends we could rm:

media_vimeo
simple_gmap
tablefield
views_autocomplete_filters
list
media_youtube seem

**Comment by jlyon** [comment]
Currently the image fieldable panel pane has a display mode that shows a broken image (panopoly image style that doesn't exist). Would be nice to get that defaulting to Flexible Media.

**Comment by aschmoe** [comment]
This has happened
