### ISSUE TITLE
Wait, what is the name of this thing?

### ISSUE THREAD

**Issue by jodyHamilton** [albatrossdigital/helm#84]
I followed a link from https://www.drupal.org/project/ckeditor_widgets that said that I was going to be looking at a distribution called 'Soar'. This took me here, to 'Helm'.

Your Helm README says Helm is the next generation of 'Flight'.

'Flight' project page says it's morphing into 'Proud'.

Ummm. What?

**Comment by jlyon** [comment]
Sorry for all of the confusion Jody, and thanks for your interest.  We're working on re-packaging everything (ckeditor widgets, some work we have been doing with the panels interface) into an entirely new distro (for a new company) called Proud.  It's not quite ready, but the CKEditor/CKEditor widgets integration does work in the Github repo: https://github.com/proudcity/proud-drops.

Thanks for pointing out the bad links on the ckeditor_widgets doc page.  I just updated the link to  It had been on my todo list for a few weeks (months) now.   I know it's confusing to have links pointing to defunct projects (and bad for the community in general to have defunct projects).  I updated the module description page. The feature at https://github.com/proudcity/proud-drops/tree/7.x-1.x/profiles/proud/modules/features/proud_input_formats sets up the various CKEditor widgets settings.
