### ISSUE TITLE
views_data_export needed for helm_news views

### ISSUE THREAD

**Issue by aschmoe** [albatrossdigital/helm#9]
So we need to move into the app phase, or retain this in profiles/helm/modules

**Comment by jlyon** [comment]
yeah i was noticing this as well. i want to get rid of these dependencies.

i also want to switch over to using services_views instead of views_data_export

**Comment by jlyon** [comment]
nvm #6. This is needed for angular_media for now

**Comment by jlyon** [comment]
dupe closing
